# Generated by Django 4.2.2 on 2023-06-19 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100, unique=True)),
                ('check_type', models.CharField(max_length=100)),
                ('point_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтери',
                'db_table': 'printer',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('order', models.JSONField()),
                ('status', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receipt.printer')),
            ],
        ),
    ]
