# Generated by Django 4.2.2 on 2023-06-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_alter_check_options_alter_check_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
